name: Create PR and Merge using github script
on:
  pull_request:
    types: [labeled]
    branches:
      - master

jobs:
  create-pr-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Create branch
        uses: actions/github-script@v4
        with:
          script: |
            console.log(context)
