name: Create PR and Merge using github script
on:
  pull_request:
    types: [labeled]
    branches:
      - master

jobs:
  create-pr-and-merge:
    if: ${{ github.event.label.name == 'automerge' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create branch
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
          # github.repos.merge({
          #   owner: context.repo.owner,
          #   repo: context.repo.repo,
          #   base: context.payload.pull_request.base.ref
          #   head: context.payload.pull_request.head.ref
          # })
