name: Create PR and Merge using github script
on:
  pull_request:
    branches:
      - "update-manifest/ohmy/dev/**"
  label:
    types: [created, edited]

jobs:
  create-pr-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create branch
        uses: actions/github-script@v4
        with:
          script: |
            console.log(context)
