name: Test ECR output 
on: 
  push:
    branches:
      - ecr-output/**

jobs:
  login-aws-and-ecr:
    environment: development
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Print registry
        env: 
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: echo $REGISTRY
