name: Generate encrypted secret
on:
  workflow_dispatch:
    inputs:
      secret:
        description: "Value of the secret"
        required: true
      repository:
        description: "Name of repository"
        required: true
      environment:
        description: "Environment of the repository"
        required: true

jobs:
  create-encyrpted-secret:
    runs-on: ["self-hosted", "linux", "x64", "nomad"]

    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Update Image Tag
        env:
          PAT: ${{ secrets.ORG_MACHINE_USER_PAT }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          REPOSITORY: ${{ github.event.inputs.repository }}
          SECRET: ${{ github.event.inputs.secret }}
        run: |
          pip install pynacl requests
          python .github/replace-image-tag.py $PAT $REPOSITORY $ENVIRONMENT $SECRET
