name: Test teams notification
on: push
jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Microsoft Teams Deploy Card
        uses: toko-bifrost/ms-teams-deploy-card@3.1.2
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URI_GITHUB }}
      - name: Test is a test
        run: echo "This is the start of the test"
