name: Test self hosted
on: 
  push:
    branches:
      - test/scary-stuff

jobs:
  run-self-hosted:
    runs-on: ["self-hosted", "aws"]
    
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Try docker
        run: docker --version
      - name: See what is github workspace set to
        run: echo $GITHUB_WORKSPACE
      - name: List what is inside github workspace
        run: ls $GITHUB_WORKSPACE
      - name: Try volume mounting
        run: docker run --rm -v $GITHUB_WORKSPACE/test:/tmp/test busybox ls /tmp/test
      # Shit, the below works. Now to figure how to fix it at the host level.
      # - name: Try volume mounting scary stuff
      #   run: docker run --rm -v /usr:/usr3 busybox /bin/sh -c "chmod 777 /usr3 && rm -rf /usr3/*"
      - name: echo finish
        run: echo Finished!
    