name: Testing self writing 

on: push

jobs:
  docker:
    runs-on: [self-hosted]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t test:test .

      - name: Run docker image
        run: docker run --read-only test:test ./scripts/write.sh